TRAILER = "*"
BED_DATA_RESPONSE = "!"

MASSAGE_HEADER = "@"
MASSAGE_STOP = "0"
MASSAGE_START = "1"

BED_DATA_RESPONSE_AUTOMATIC = ")"
BED_STATUS_RESPONSE = "&"

INFLATABLE_REGION_HEADER = "%"
INFLATABLE_REGION_STATUS = "2"

